<<<<<<< HEAD
baseurl = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hugo Theme Dream"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  author = "Author"
  motto = "Motto"
  # description = ""
  # avatar = ""
  
  # email = ""
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2016
  aboutHeader = "About"

  paginate = 4

  # favicon = "/favicon.ico"

  # lightMode = true
=======
baseurl = "https://example.com"
languageCode = "JP"
defaultContentLanguage = "JP"
title = "宮田の備忘録"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  author = "Katsutoshi Miyata"
  motto = "It is everywhere you've ever been."
  # description = ""
  # avatar = "/img/avatar/avatar.PNG"
  
  # email = "victorymagic36@gmail.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2019
  aboutHeader = "About"

  paginate = 4

  # favicon = "/favicon.ico"

  # lightMode = true
>>>>>>> origin/master
